# Generated by Django 5.2.17 on 2026-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('verify_token', models.CharField(blank=True, db_collation='utf8mb4_bin', db_index=True, max_length=64, null=True)),
                ('reset_token', models.CharField(blank=True, db_collation='utf8mb4_bin', db_index=True, max_length=64, null=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('name', models.CharField(db_collation='utf8mb4_bin', max_length=255, primary_key=True, serialize=False)),
                ('path', models.CharField(default='uploads', max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=127)),
                ('size', models.BigIntegerField(default=0)),
                ('owner', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(db_collation='utf8mb4_bin', max_length=64)),
                ('doc_id', models.CharField(db_collation='utf8mb4_bin', max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['collection', 'created_at'], name='idx_collection_created')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'doc_id'), name='uniq_collection_doc')],
            },
        ),
    ]
